### ISSUE TITLE
Invalid Video ID on Landscape Rotation 

### ISSUE THREAD

**Issue by thivankasarathchandra** [sarbagyastha/youtube_player_flutter#118]
Player is working on normal view. When the full screen selected  player shows
 " Invalid Video ID =   --the_video_id--
Error Code = 1"

Exiting the full screen restore the player to portrait and works normally.

Checked on both Emulator and Physical device (Android Only).

Yes the sample app has the same results. Please check this. 
In both version 6.0.0 and 6.0.2
Any way awesome Plugin. Thank You

**Comment by sarbagyastha** [comment]
@thivankasarathchandra  Fixed in [**Version 6.0.3+1**](https://pub.dev/packages/youtube_player_flutter#6031)

**Comment by thivankasarathchandra** [comment]
Issue Fixed ! 
Thank you.

**Comment by thangmam** [comment]
Hello, this issue still exists.I am using package version ^6.1.0+4.I am using Redmi k20 pro for testing.I get errors like below 

`W/PlatformViewsController(17723): Creating a virtual display of size: [1080, 2340] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2210].
D/EgretLoader(17723): EgretLoader(Context context)
D/EgretLoader(17723): The context is not activity
I/flutter (17723): The controller is not ready for method calls.
W/ContentCatcher(17723): Failed to notify a WebView
W/PlatformViewsController(17723): Creating a virtual display of size: [1080, 2340] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [2340, 1080].
D/EgretLoader(17723): EgretLoader(Context context)
D/EgretLoader(17723): The context is not activity
W/ContentCatcher(17723): Failed to notify a WebView
W/ContentCatcher(17723): Failed to notify a WebView
W/ContentCatcher(17723): Failed to notify a WebView
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
W/OpenGLRenderer(17723): swapBuffers encountered EGL error 12301 on 0x783bf7ed00, halting rendering...
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
W/ContentCatcher(17723): Failed to notify a WebView
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
W/OpenGLRenderer(17723): swapBuffers encountered EGL error 12301 on 0x783bc54380, halting rendering...
W/ContentCatcher(17723): Failed to notify a WebView
I/Presentation(17723): Presentation is being dismissed because the display metrics have changed since it was created.
I/chromium(17723): [INFO:CONSOLE(228)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflaP-XGF/www-widgetapi.js (228)
I/chromium(17723): [INFO:CONSOLE(228)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflaP-XGF/www-widgetapi.js (228)
W/PlatformViewsController(17723): Creating a virtual display of size: [1080, 2340] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2210].
W/ContentCatcher(17723): Failed to notify a WebView
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
W/ContentCatcher(17723): Failed to notify a WebView
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
I/Adreno  (17723): DequeueBuffer: dequeueBuffer failed
W/OpenGLRenderer(17723): swapBuffers encountered EGL error 12301 on 0x7834ba7c00, halting rendering...
I/Presentation(17723): Presentation is being dismissed because the display metrics have changed since it was created.
I/chromium(17723): [INFO:CONSOLE(83)] "Uncaught TypeError: player.playVideo is not a function", source: https://www.youtube.com/ (83)
I/chromium(17723): [INFO:CONSOLE(83)] "Uncaught TypeError: player.playVideo is not a function", source: https://www.youtube.com/ (83)
I/chromium(17723): [INFO:CONSOLE(88)] "Uncaught TypeError: player.pauseVideo is not a function", source: https://www.youtube.com/ (88)
I/chromium(17723): [INFO:CONSOLE(228)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflaP-XGF/www-widgetapi.js (228)
I/chromium(17723): [INFO:CONSOLE(228)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflaP-XGF/www-widgetapi.js (228)
D/AudioTrack(17723): stop(sessionID=60977)
D/AudioTrack(17723): ~AudioTrack(sessionID=60977)
D/AudioTrack(17723): stop(sessionID=60977)
D/        (17723): TrackPlayerBase::~TrackPlayerBase()
D/        (17723): PlayerBase::~PlayerBase()
W/System  (17723): A resource failed to call release.`

**Comment by guillermogranfer** [comment]
Issue persint in 6.1.0+4 but only in live videos
