### ISSUE TITLE
[BUG] Error 150 on some videos

### ISSUE THREAD

**Issue by EliasDeuss** [sarbagyastha/youtube_player_flutter#119]
This is the video: https://www.youtube.com/watch?v=GUqcY8WNTZs

Error: The owner of the requested video may not allow it to be played.

Video embedding is turned on for the video and other videos.

**Comment by sarbagyastha** [comment]
Error 150 is not well documented. Couldn't figure out why its not playing the video. 
Also, the thumbnail for the video is not available https://i3.ytimg.com/vi_webp/GUqcY8WNTZs/sddefault.webp

**Comment by EliasDeuss** [comment]
I think it's because it has copyrighted music in it.

**Comment by sarbagyastha** [comment]
Oh yes @EliasDeuss , tested 5 videos from the same channel and videos with no copyrighted music played without **150** , whereas videos with copyrighted music returned with **150**.

**Comment by EliasDeuss** [comment]
@sarbagyastha There should be option to open the video on Youtube if not available in the player.

**Comment by sarbagyastha** [comment]
@EliasDeuss You can implement it on your own by listening to the errors.

**Comment by tagerjump** [comment]
This error doesn't for 4.1.0 or lower version

**Comment by letiagoalves** [comment]
I can confirm. I tried to upgrade from 4.1.0 to latest version and just now I get this error. Never had it using version 4.1.0. What changed?

**Comment by TheBestMoshe** [comment]
@sarbagyastha How are we supposed to catch playback errors?

I am trying to embed YouTube videos but some of them are restricted to only play on a specific domain. I want to try to catch this error before even showing the play button and instead show that it can't be played. Is there a way to do this?

The best would be if we could play with the referrer headers. [This StackOverflow post](https://stackoverflow.com/a/36952048/9642772) makes it seem like it's possible. Is there any way to do this with this plugin?

**Comment by EliasDeuss** [comment]
@sarbagyastha I think what @TheBestMoshe suggested might fix most of the Error 150 issues

**Comment by sarbagyastha** [comment]
@TheBestMoshe Thank you for pointing out. I will definitely look into it.

**Comment by mayurdhurpate** [comment]
Here's what I found so far:

**Error Overview**

`youtube_player_flutter` uses Youtube IFrame API for embedding Youtube player using flutter_webview, and the IFRAME API is producing the error. Here's the link to view all the errors that the player may receive: https://developers.google.com/youtube/iframe_api_reference#Events

The ones associated with Error 150 are:
`101` – The owner of the requested video does not allow it to be played in embedded players.
`150` – This error is the same as 101. It's just a 101 error in disguise!

Which means the video owners have disabled the videos to be played embedded. 

**Video Metadata**
I tried checking the `embeddable`, `restricted` and other properties of videos which were not working using the [YouTube Data API](https://developers.google.com/youtube/v3/getting-started) to get the key:

`https://www.googleapis.com/youtube/v3/videos?id=[VIDEO_ID]&key=[API_KEY]&part=snippet,contentDetails,status`

I couldn't find any difference in the metadata of the videos which were blocked and unblocked.

**Error Reporting**
In the `RawYoutubePlayer` widget internally used by the plugin, on error occurrence, error code (e.g. 150) is set as the value for `controller.value` here:
https://github.com/sarbagyastha/youtube_player_flutter/blob/6f21d8b25019394257c71b7399c9199ee5198a17/lib/src/player/raw_youtube_player.dart#L175-L181

I think `controller.value` could be monitored for error reporting and handling, though better handling using `onError` method exposed, and some info in the documentation would be very helpful too.

**Comment by hgadjan** [comment]
I have the same issue, even using **my own videos**

**Comment by zcr1** [comment]
I tried using `4.1.0` but was not able to get the example to work in that repo. One difference is the `origin` field in `playerVars` is no longer set. Unfortunately, after setting this the videos which had a `150` error before just hang and no events are fired from the api.

**Comment by zcr1** [comment]
Additionally I was able to embed the video using https://github.com/hoanglm4/flutter_youtube_view

**Comment by Ali1Ammar** [comment]
same error  with all kind video 
not special one  include example video

**Comment by namchuai** [comment]
Any update on this issue?

**Comment by sarbagyastha** [comment]
Fixed with Version 6.1.0

**Comment by namchuai** [comment]
The issue is solved. Thank you!

**Comment by dessteyu** [comment]
hi,
i still have this error on 6.1.0+4.

**Comment by divya21raj** [comment]
The issue still persist-> [This video ](https://www.youtube.com/watch?v=OUhE_FaJRqY)

**Comment by simp13** [comment]
I still have this error on android emulator but work on real device.
Could you please tell me why?

**Comment by eic1223** [comment]
hi, from s.korea
i still have this error, too.
the video i wanna play is copyrighted video(MV).
i can play on emulator, but cannot play on real device (Pixel 3) via google play released. No error message, loading circle runs infinitely. 

anyone like me?

**Comment by whatamelon** [comment]
it still persist.
even if the video contain sound cloud's music, not copyright by youtube.

**Comment by edgarfroes** [comment]
Still persisting to this day.

**Comment by edgarfroes** [comment]
With me, the problem was that I lowered all case on the video id, and it's case sensitive. Instead of YE7VzlLtp-4, I was sending ye7vzlltp-4.

**Comment by mmustafaget** [comment]
> I had the same issue and managed to solve it by changing the origin.
> 
> If it helps, you can also use the [omni_video_player](https://pub.dev/packages/omni_video_player/changelog) library, which makes handling the video player much easier

i had same error coming in omini player
