### ISSUE TITLE
BoxConstraints has a negative minimum height.

### ISSUE THREAD

**Issue by baptisteArnaud** [sarbagyastha/youtube_player_flutter#72]
Hello,

I'm trying to implement a small floating player so I set the width at 100.0 but it throws the following error :

```
════════ (1) Exception caught by widgets library ══════════
BoxConstraints has a negative minimum height.
User-created ancestor of the error-causing widget was: 
  YoutubePlayer file:///C:/Dev/turn-up/frontend/lib/screens/player.dart:22:15
════════════════════════════════════════════
```

**Comment by sarbagyastha** [comment]
@baptisteArnaud Fixed in Version 5 and up.

**Comment by Trend74X** [comment]
I still have this issue when full screen is enabled. 
youtube_player_flutter: ^9.0.3
