### ISSUE TITLE
player stuck in loading state

### ISSUE THREAD

**Issue by MagarKJ** [sarbagyastha/youtube_player_flutter#955]
E/flutter (26747): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (26747): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (26747): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (26747): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (26747): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (26747): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (26747): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (26747): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (26747): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter (26747): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (26747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (26747): )
E/flutter (26747): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (26747): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (26747): <asynchronous suspension>
E/flutter (26747): #2      ExpensiveAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1099:5)
E/flutter (26747): <asynchronous suspension>
E/flutter (26747): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:822:5)
E/flutter (26747): <asynchronous suspension>
E/flutter (26747): 
![Screenshot (89)](https://github.com/sarbagyastha/youtube_player_flutter/assets/107093272/08cc8b7c-5628-4743-9f40-9188c9b19061)
![Screenshot (90)](https://github.com/sarbagyastha/youtube_player_flutter/assets/107093272/21f0dbcd-72ca-4961-a328-61dfa01ff83c)
![Screenshot (91)](https://github.com/sarbagyastha/youtube_player_flutter/assets/107093272/4441fcd0-e50a-4486-80de-156e6526b745)
![Screenshot (92)](https://github.com/sarbagyastha/youtube_player_flutter/assets/107093272/263e1f42-4ab0-48e7-b021-2ea68095eab0)

**Comment by CoderNamedHendrick** [comment]
Is the issue from this package or in_app_webview @sarbagyastha ?

**Comment by vko85** [comment]
However the package run on android, I notice the same on iOS that it stuck on loading phase. So as you pointed out inappwebview may hold the solution and due to the fact that I didn't see it among the installed packages i've added to dependencies. As soon as it deployed the inappwebview 5.8.0 package it solved my issue.

**Comment by vko85** [comment]
@CoderNamedHendrick thats right.

**Comment by CoderNamedHendrick** [comment]
@vko85 I tried that and couldn't compile my app

**Comment by CoderNamedHendrick** [comment]
Overriding the youtube_player_flutter to an earlier version solves the problem.

Add this to my dependency_overrides
youtube_player_flutter: 8.1.2

**Comment by vko85** [comment]
@CoderNamedHendrick sorry, yes I was using these two versions too.
  youtube_player_flutter: ^8.1.2
  flutter_inappwebview: ^5.8.0

**Comment by novas1r1** [comment]
Thank you, downgrading youtube_player_flutter: ^8.1.2 fixed it for me as well.

**Comment by TijnvandenEijnde** [comment]
Unfortunately, the bug has not been addressed in version [9.0.2](https://pub.dev/packages/youtube_player_flutter/versions/9.0.2) as the YouTube player is constantly showing a loading spinner even when playing the video.

**Comment by Constans** [comment]
[9.0.3](https://pub.dev/packages/youtube_player_flutter/changelog#903) mentions that it addressed the issue but it's still present for Android devices...

**Comment by TijnvandenEijnde** [comment]
@matmicro, I haven't tested the new version yet, but I still use [8.1.2](https://pub.dev/packages/youtube_player_flutter/changelog#812).

Here is how I implemented it: https://onlyflutter.com/how-to-display-youtube-videos-in-flutter/
